--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/JobGUI
build-by-default: true
branches:
- main
projects:
  JobGUI:
    path: ""
    - src: muqsit/invMenu/Invmenu
      version: ^1.0.0
...
